import A from "@/components/A";
import Head from "next/head";

const MainContainer = ({ children, keywords }) => {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content={"next js, artem lepeshkin" + keywords}
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar">
        <A href="/" text="Main"></A>
        <A href="/users" text="Users"></A>
      </div>
      <div>{children}</div>
      <style jsx>{`
        .navbar {
          background-color: orange;
          padding: 15px;
        }
      `}</style>
    </>
  );
};

export default MainContainer;
